INSERT OVERWRITE LOCAL DIRECTORY '/home/ponny/Project/Outdata' Select AIRLINE,COUNT(ARRIVAL_DELAY)AS T FROM fly where ARRIVAL_DELAY>0 GROUP BY AIRLINE ORDER BY T DESC ;
RAW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
