create table Fly
(DAY STRING,
DAY_OF_WEEK STRING,
AIRLINE STRING,
FLIGHT_NUMBER STRING,
ORIGIN_AIRPORT STRING,
DESTINATION_AIRPORT STRING,
DEPARTURE_TIME STRING,
DEPARTURE_DELAY STRING,
SCHEDULED_TIME STRING,
ELAPSED_TIME STRING,
AIR_TIME STRING,
DISTANCE STRING,
SCHEDULED_ARRIVAL STRING,
ARRIVAL_TIME STRING,
ARRIVAL_DELAY STRING,
DIVERTED STRING,
CANCELLED STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
DESCRIBE Fly;
load data inpath '/home/LSProj/FlyData' into table Fly;
select * from Fly limit 10;
