create table predictions(DAY INT,DAY_OF_WEEK INT,AIRLINE STRING,FLIGHT_NUMBER INT,ORIGIN_AIRPORT STRING,DESTINATION_AIRPORT STRING,
DEPARTURE_TIME INT,DEPARTURE_DELAY INT,SCHEDULED_TIME INT,
ELAPSED_TIME INT,AIR_TIME INT,DISTANCE INT,
SCHEDULED_ARRIVAL INT,ARRIVAL_TIME INT,ARRIVAL_DELAY INT,DIVERTED INT,
CANCELLED INT)ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' LOCATION 
'/user/ponny/Predictions';
DESCRIBE predictions;
load data inpath '/user/ponny/LSData' into table predictions;
